name: Test alerts

on:
  push:
    branches-ignore:
      - development/**
      - q/*/**

jobs:
  run-alert-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Render and test lifecycle 
        uses: scality/action-prom-render-test@1.0.2
        with:
          alert_file_path: monitoring/lifecycle/alerts.yaml
          test_file_path: monitoring/lifecycle/alerts.test.yaml
          alert_inputs: >-
            namespace=zenko,job_lifecycle_producer=artesca-data-backbeat-lifecycle-producer-headless,job_lifecycle_bucket_processor=artesca-data-backbeat-lifecycle-bucket-processor-headless,job_lifecycle_object_processor=artesca-data-backbeat-lifecycle-object-processor-headless,lifecycle_conductor_replicas=1,lifecycle_bucket_replicas=3,lifecycle_object_replicas=3
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Render and test replication 
        uses: scality/action-prom-render-test@1.0.2
        with:
          alert_file_path: monitoring/replication/alerts.yaml
          test_file_path: monitoring/replication/alerts.test.yaml
          alert_inputs: >-
            namespace=zenko,job_queue_populator=backbeat-replication-producer-headless,job_data_processor=backbeat-replication-data-processor-headless,job_replay_processor=backbeat-replication-replay-processor-headless,job_status_processor=backbeat-replication-status-processor-headless,queue_populator_replicas=1,data_processor_replicas=3,replay_processor_replicas=3,status_processor_replicas=3,replicationErrorsWarningThreshold=0.1,replicationErrorsCriticalThreshold=1,rpoWarningThreshold=600,rpoCriticalThreshold=900,latencyWarningThreshold=3000,latencyCriticalThreshold=6000
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Render and test notification 
        uses: scality/action-prom-render-test@1.0.2
        with:
          alert_file_path: monitoring/notification/alerts.yaml
          test_file_path: monitoring/notification/alerts.test.yaml
          alert_inputs: >-
            namespace=zenko,job_notification_producer=artesca-data-backbeat-notification-producer-headless,job_notification_processors=artesca-data-backbeat-notification-processor,notificationFailuresWarningThreshold=0.1,notificationFailuresCriticalThreshold=0.5,notification_producer_replicas=3,notification_processor_replicas=2
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}

      - name: Render and test oplog populator 
        uses: scality/action-prom-render-test@1.0.2
        with:
          alert_file_path: monitoring/oplog-populator/alerts.yaml
          test_file_path: monitoring/oplog-populator/alerts.test.yaml
          alert_inputs: >-
            namespace=zenko,oplog_populator_job=artesca-data-backbeat-oplog-populator-headless,oplogPopulatorChangeStreamLagThreshold=10
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
